version: '2.1'

services:
  nodesite:
    image: nodesite
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 9229:9229
    ##  - 3000:3000
    ##  - 9229:9229
    ## set your startup file here
    ##command: node --inspect index.js
    command: npm --inspect start